export enum VoiceSpeaker {
  // English
  GameOn = "en_male_jomboy",
  Jessie = "en_us_002",
  Warm = "es_mx_002",
  Wacky = "en_male_funny",
  Scream = "en_us_ghostface",
  Empathetic = "en_female_samc",
  Serious = "en_male_cody",
  BeautyGuru = "en_female_makeup",
  Bestie = "en_female_richgirl",
  Trickster = "en_male_grinch",
  Joey = "en_us_006",
  StoryTeller = "en_male_narration",
  MrGoodGuy = "en_male_deadpool",
  Narrator = "en_uk_001",
  MaleEnglishUK = "en_uk_003",
  Metro = "en_au_001",
  Alfred = "en_male_jarvis",
  ashmagic = "en_male_ashmagic",
  olantekkers = "en_male_olantekkers",
  LordCringe = "en_male_ukneighbor",
  MrMeticulous = "en_male_ukbutler",
  Debutante = "en_female_shenna",
  Varsity = "en_female_pansino",
  Marty = "en_male_trevor",
  PopLullaby = "en_female_f08_twinkle",
  ClassicElectric = "en_male_m03_classical",
  Bae = "en_female_betty",
  Cupid = "en_male_cupid",
  Granny = "en_female_grandma",
  Cozy = "en_male_m2_xhxs_m03_christmas",
  Author = "en_male_santa_narration",
  Caroler = "en_male_sing_deep_jingle",
  Santa = "en_male_santa_effect",
  NYE2023 = "en_female_ht_f08_newyear",
  Magician = "en_male_wizard",
  Opera = "en_female_ht_f08_halloween",
  Euphoric = "en_female_ht_f08_glorious",
  Hypetrain = "en_male_sing_funny_it_goes_up",
  Melodrama = "en_female_ht_f08_wonderful_world",
  QuirkyTime = "en_male_m2_xhxs_m03_silly",
  Peaceful = "en_female_emotional",
  ToonBeat = "en_male_m03_sunshine_soon",
  OpenMic = "en_female_f08_warmy_breeze",
  Jingle = "en_male_m03_lobby",
  Thanksgiving = "en_male_sing_funny_thanksgiving",
  Cottagecore = "en_female_f08_salut_damour",
  Professor = "en_us_007",
  Scientist = "en_us_009",
  Confidence = "en_us_010",
  Smooth = "en_au_002",

  // Disney
  GhostFaceDisney = "en_us_ghostface",
  Chewbacca = "en_us_chewbacca",
  C3PO = "en_us_c3po",
  Stitch = "en_us_stitch",
  Stormtrooper = "en_us_stormtrooper",
  Rocket = "en_us_rocket",
  MadameLeota = "en_female_madam_leota",
  GhostHost = "en_male_ghosthost",
  Pirate = "en_male_pirate",

  // French
  FrenchMale1 = "fr_001",
  FrenchMale2 = "fr_002",

  // Spanish
  SpanishSpainMale = "es_002",
  SpanishMXMale = "es_mx_002",

  // Portuguese
  PortugueseBRFemale1 = "br_001",
  PortugueseBRFemale2 = "br_003",
  PortugueseBRFemale3 = "br_004",
  PortugueseBRMale = "br_005",
  IveteSangalo = "bp_female_ivete",
  Ludmilla = "bp_female_ludmilla",
  LhaysMacedo = "pt_female_lhays",
  Laizza = "pt_female_laizza",
  GalvaoBueno = "pt_male_bueno",

  // German
  GermanFemale = "de_001",
  GermanMale = "de_002",

  // Indonesian
  IndonesianFemale = "id_001",

  // Japanese
  JapaneseFemale1 = "jp_001",
  JapaneseFemale2 = "jp_003",
  JapaneseFemale3 = "jp_005",
  JapaneseMale = "jp_006",
  Risa = "jp_female_fujicochan",
  Serasu = "jp_female_hasegawariona",
  MoriosKitchen = "jp_male_keiichinakano",
  NatsueCoco = "jp_female_oomaeaika",
  TeionVoice = "jp_male_yujinchigusa",
  Shiro = "jp_female_shirou",
  TamakawaToshiki = "jp_male_tamawakazuki",
  ShojiKaori = "jp_female_kaorishoji",
  YagiSaki = "jp_female_yagishaki",
  Hikakin = "jp_male_hikakin",
  MaruyamaRei = "jp_female_rei",
  Shuichiro = "jp_male_shuichiro",
  MatsudaFamilyRoutine = "jp_male_matsudake",
  Machikoriita = "jp_female_machikoriiita",
  Mojao = "jp_male_matsuo",
  Morisuke = "jp_male_osada",

  // Korean
  KoreanMale1 = "kr_002",
  KoreanFemale = "kr_003",
  KoreanMale2 = "kr_004",

  // Vietnamese
  VietnameseFemale = "BV074_streaming",
  VietnameseMale = "BV075_streaming",

  // Other
  Alto = "en_female_f08_salut_damour",
  Tenor = "en_male_m03_lobby",
  SunshineSoon = "en_male_m03_sunshine_soon",
  WarmyBreeze = "en_female_f08_warmy_breeze",
  Glorious = "en_female_ht_f08_glorious",
  ItGoesUp = "en_male_sing_funny_it_goes_up",
  Chipmunk = "en_male_m2_xhxs_m03_silly",
  Dramatic = "en_female_ht_f08_wonderful_world",
}

export enum Language {
  EN = VoiceSpeaker.Jessie,
  ES = VoiceSpeaker.Warm,
  FR = VoiceSpeaker.FrenchMale1,
  PT = VoiceSpeaker.PortugueseBRFemale1,
  DE = VoiceSpeaker.GermanFemale,
  ID = VoiceSpeaker.IndonesianFemale,
  JP = VoiceSpeaker.JapaneseFemale1,
  KR = VoiceSpeaker.KoreanMale1,
  VN = VoiceSpeaker.VietnameseFemale,
}
